name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make Gradlew Executable
        run: |
          chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          export PORT_APP=${{ vars.PORT_APP }}
          ./gradlew build

      - name: Copy Project to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_EC2 }}
          username: ${{ secrets.USERNAME_EC2 }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "./"
          target: "/reto-comfama"

      - name: SSH into EC2 and Run Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_EC2 }}
          username: ${{ secrets.USERNAME_EC2 }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ../reto-comfama/scripts/
            export PORT_APP=${{ vars.PORT_APP }}
            bash docker_process.sh